# Generated by Django 6.0.6 on 2026-07-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='expired_at',
            new_name='expires_at',
        ),
    ]
