# Generated by Django 6.0.6 on 2026-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_expired_at_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(verbose_name='expires at'),
        ),
    ]
