# Generated by Django 6.0.7 on 2026-08-21 09:25

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_alter_otpcode_phone'),
        ('orders', '0006_alter_order_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='orders_orde_status_62907b_idx'),
        ),
    ]
