# Generated by Django 6.0.7 on 2026-08-23 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_token_order_orders_orde_status_62907b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('aqayepardakht', 'aqayepardakht')], default='aqayepardakht', max_length=20, verbose_name='gateway')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='gateway reference')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='status')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='raw response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('authority__gt', '')), fields=('gateway', 'authority'), name='unique_gateway_authority')],
            },
        ),
    ]
