# Generated by Django 6.0.7 on 2026-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('badge', models.TextField(verbose_name='badge')),
                ('credentials', models.JSONField(blank=True, default=dict, verbose_name='credentials')),
                ('origin', models.CharField(choices=[('aqayepardakht', 'aqayepardakht'), ('zarinpal', 'zarinpal')], max_length=50, verbose_name='origin')),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'gateway',
                'verbose_name_plural': 'gateways',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
