# Generated by Django 6.0.7 on 2026-08-26 11:49

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_alter_otpcode_phone'),
        ('catalog', '0015_category_image_dark_collection_image_dark'),
        ('orders', '0009_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='converted at'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='max_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='maximum amount'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='min_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='minimum amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.cart', verbose_name='cart'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='options'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(max_length=64, null=True, verbose_name='sku'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='reference id'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='badge',
            field=models.TextField(blank=True, verbose_name='badge'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='order number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'pending payment'), ('processing', 'processing'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('expired', 'expired'), ('refunded', 'refunded')], default='pending_payment', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant', verbose_name='variant'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='authority',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='authority'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.gateway', verbose_name='gateway'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_item_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='gateway',
            constraint=models.CheckConstraint(condition=models.Q(('max_amount__isnull', True), ('min_amount__isnull', True), ('max_amount__gte', models.F('min_amount')), _connector='OR'), name='gateway_max_amount_gte_min_amount'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_amount'), '+', models.F('shipping_amount')), '-', models.F('discount_amount')))), name='order_total_amount_consistent'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_price', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='order_item_total_price_consistent'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='unique_pending_transaction_per_order'),
        ),
    ]
