# Generated by Django 6.0.7 on 2026-08-26 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_sku_alter_orderitem_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'updated_at'], name='orders_cart_user_id_2871a4_idx'),
        ),
    ]
