# Generated by Django 6.0.7 on 2026-08-29 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cart_orders_cart_user_id_2871a4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='badge',
            field=models.FileField(blank=True, null=True, upload_to='payment-badges', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='badge'),
        ),
    ]
