# Generated by Django 6.0.7 on 2026-08-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_gateway_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='badge',
            field=models.FileField(blank=True, null=True, upload_to='payment-badges', verbose_name='badge'),
        ),
    ]
