# Generated by Django 6.0.7 on 2026-09-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_gateway_badge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
