# Generated by Django 6.0.7 on 2026-09-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='origin',
            field=models.CharField(choices=[('aqayepardakht', 'aqayepardakht'), ('zarinpal', 'zarinpal'), ('zibal', 'zibal')], max_length=50, verbose_name='origin'),
        ),
    ]
