# Generated by Django 6.0.7 on 2026-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_gateway_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='is installment'),
        ),
    ]
