# Generated by Django 6.0.7 on 2026-09-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_gateway_is_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='origin',
            field=models.CharField(choices=[('aqayepardakht', 'aqayepardakht'), ('zarinpal', 'zarinpal'), ('zibal', 'zibal'), ('digipay', 'digipay')], max_length=50, verbose_name='origin'),
        ),
    ]
