# Generated by Django 6.0.7 on 2026-09-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_gateway_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
