# Generated by Django 6.0.6 on 2026-07-09 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                (
                    'province',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='recipient name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('address_line', models.TextField(verbose_name='address')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='addresses',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
                (
                    'city',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='accounts.city', verbose_name='city'
                    ),
                ),
                (
                    'province',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='accounts.province', verbose_name='province'
                    ),
                ),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_default', True)),
                        fields=('user',),
                        name='unique_default_address_per_user',
                    )
                ],
            },
        ),
    ]
