# Generated by Django 6.0.7 on 2026-08-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_city_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='phone'),
        ),
    ]
