server {
    listen 80;
    server_name api.starboy.ir;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name api.starboy.ir;

    client_max_body_size 50M;

    ssl_certificate     /etc/nginx/ssl/starboy.ir/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/starboy.ir/privkey.pem;

	# Set this if you want to serve medias locally
    # location /media/ {
    #     alias /var/www/starboy/media/;
    # }
 
    location / {
        proxy_pass http://127.0.0.1:8000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
