[project]
name = "pen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleach==6.4.0",
    "boto3>=1.43.67",
    "django==6.0.7",
    "django-cors-headers==4.9.0",
    "django-filter==26.1",
    "django-storages>=1.14.6",
    "django-unfold==0.101.0",
    "django-unfold-markdown==0.1.2",
    "djangorestframework==3.17.1",
    "drf-spectacular[sidecar]==0.30.0",
    "gunicorn>=26.0.0",
    "markdown==3.10.2",
    "pillow==12.3.0",
    "psycopg[binary]==3.3.4",
    "requests==2.34.2",
    "smsir-python==1.0.8",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
]

[tool.ruff]
line-length = 120
exclude = [
	"**/migrations/**",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]


[tool.ruff.format]
quote-style = "single"
