# Generated by Django 6.0.7 on 2026-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('html', models.TextField(verbose_name='html')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Footer Badge',
                'verbose_name_plural': 'Footer Badges',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
