# Generated by Django 6.0.7 on 2026-08-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerbadge',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'footer badge', 'verbose_name_plural': 'footer badges'},
        ),
    ]
