# Generated by Django 6.0.7 on 2026-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_footerbadge_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('badge', models.TextField(verbose_name='badge')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment gateway',
                'verbose_name_plural': 'payment gateways',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='footerbadge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
