# Generated by Django 6.0.7 on 2026-08-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentgateway_alter_footerbadge_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='base_url',
            field=models.URLField(default='https://api.starboy.ir', verbose_name='base url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='merchant_id',
            field=models.CharField(default='123456789', max_length=200, unique=True, verbose_name='merchant id'),
            preserve_default=False,
        ),
    ]
