# Generated by Django 6.0.7 on 2026-08-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentgateway_base_url_paymentgateway_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
