# Generated by Django 6.0.7 on 2026-09-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerbadge',
            name='html_2',
            field=models.TextField(blank=True, null=True, verbose_name='html 2'),
        ),
    ]
