# Generated by Django 6.0.7 on 2026-09-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_footerbadge_html_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rate', models.DecimalField(decimal_places=0, max_digits=20)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['currency', '-fetched_at'], name='core_exchan_currenc_74b124_idx')],
            },
        ),
    ]
