# Generated by Django 6.0.7 on 2026-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-fetched_at'], 'verbose_name': 'exchange rate', 'verbose_name_plural': 'exchange rates'},
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='fetched_at',
            field=models.DateTimeField(verbose_name='fetched at'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(blank=True, max_length=50, verbose_name='source'),
        ),
    ]
