# Generated by Django 6.0.7 on 2026-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(default='USDT', max_length=3, verbose_name='currency'),
        ),
    ]
