# Generated by Django 6.0.7 on 2026-09-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_exchangerate_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='currency'),
        ),
    ]
