# Generated by Django 6.0.7 on 2026-07-31 22:44

import apps.blog.models.post_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'post media', 'verbose_name_plural': 'post medias'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='original text in Markdown format', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, editable=False, help_text='cache rendered HTML from content — do not edit manually.', verbose_name='content html'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, help_text='short summary; if left blank, it will be automatically generated from the content.', max_length=500, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='alt text'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to=apps.blog.models.post_model.post_media_upload_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='uploaded at'),
        ),
    ]
