# Generated by Django 6.0.7 on 2026-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
