# Generated by Django 6.0.7 on 2026-08-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_alter_post_options_alter_postmedia_options_and_more'),
        ('catalog', '0011_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('description', models.CharField(max_length=160, verbose_name='description')),
                ('canonical_url', models.URLField(blank=True, verbose_name='canonical url')),
                ('is_indexable', models.BooleanField(default=True, verbose_name='is indexable')),
                ('og_title', models.CharField(blank=True, max_length=95, verbose_name='og title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='og description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='og image')),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=32, verbose_name='twitter card')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tag', to='catalog.category', verbose_name='category')),
                ('collection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tag', to='catalog.collection', verbose_name='collection')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tag', to='blog.post', verbose_name='post')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tag', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'metatag',
                'verbose_name_plural': 'metatags',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('collection__isnull', True), ('post__isnull', True), ('product__isnull', False)), models.Q(('category__isnull', False), ('collection__isnull', True), ('post__isnull', True), ('product__isnull', True)), models.Q(('category__isnull', True), ('collection__isnull', False), ('post__isnull', True), ('product__isnull', True)), models.Q(('category__isnull', True), ('collection__isnull', True), ('post__isnull', False), ('product__isnull', True)), _connector='OR'), name='metatag_exactly_one_target')],
            },
        ),
    ]
