# Generated by Django 6.0.6 on 2026-07-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('catalog', '0004_productvariant_reserved_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/customers/', verbose_name='image')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='customer name')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                (
                    'product',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customer_gallery',
                        to='catalog.product',
                        verbose_name='gallery',
                    ),
                ),
            ],
            options={
                'verbose_name': 'customer gallery image',
                'verbose_name_plural': 'customer gallery images',
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
