# Generated by Django 6.0.6 on 2026-07-11 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0004_productvariant_reserved_stock'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergallery',
            name='product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customer_gallery',
                to='catalog.product',
                verbose_name='product',
            ),
        ),
    ]
