# Generated by Django 6.0.6 on 2026-07-12 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_customergallery_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergallery',
            name='score',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='score'),
        ),
    ]
