# Generated by Django 6.0.6 on 2026-07-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title'], 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={
                'ordering': ['-published_at', '-id'],
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={
                'ordering': ['sort_order', 'id'],
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={
                'ordering': ['sort_order', 'id'],
                'verbose_name': 'product size',
                'verbose_name_plural': 'product sizes',
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='children',
                to='catalog.collection',
                verbose_name='parent',
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=80, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
