# Generated by Django 6.0.6 on 2026-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/collection/', verbose_name='image'),
        ),
    ]
