# Generated by Django 6.0.6 on 2026-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='reserved stock'),
        ),
    ]
