# Generated by Django 6.0.7 on 2026-08-02 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_review_created_at_alter_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='products/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
    ]
