# Generated by Django 6.0.7 on 2026-08-02 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='products/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='audio'),
        ),
    ]
