# Generated by Django 6.0.7 on 2026-08-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
