# Generated by Django 6.0.7 on 2026-08-02 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_audio_remove_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='products/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='audio')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('cover', models.ImageField(upload_to='products/cover', verbose_name='cover')),
                ('artist', models.CharField(max_length=100, verbose_name='artist')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'audios',
            },
        ),
    ]
