# Generated by Django 6.0.7 on 2026-08-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='attributes'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='label',
            field=models.CharField(blank=True, max_length=25, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
