# Generated by Django 6.0.7 on 2026-08-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productsize_attributes_productsize_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Custom size measurements as key/value pairs. Example: {"length": "70", "chest": "104", "sleeve": "62"}', verbose_name='attributes'),
        ),
    ]
