# Generated by Django 6.0.7 on 2026-08-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productsize_description_alter_productsize_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['id'], 'verbose_name': 'product size', 'verbose_name_plural': 'product sizes'},
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='label',
            field=models.CharField(max_length=25, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='SizeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='key')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.productsize', verbose_name='size')),
            ],
            options={
                'verbose_name': 'size attribute',
                'verbose_name_plural': 'size attributes',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
