# Generated by Django 6.0.7 on 2026-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productsize_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_dark',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/category/', verbose_name='image dark'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image_dark',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/collection/', verbose_name='image dark'),
        ),
    ]
