# Generated by Django 6.0.7 on 2026-09-13 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_category_image_dark_collection_image_dark'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='catalog_variant_compare_price_gte_price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price in USD. The displayed price is computed automatically from this value and the latest exchange rate.', max_digits=10, verbose_name='base price (USD)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='compare_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original/strikethrough price in USD. Leave empty if this variant has no discount.', max_digits=10, null=True, verbose_name='compare price (USD)'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('compare_price_usd__isnull', True), ('compare_price_usd__gte', models.F('base_price_usd')), _connector='OR'), name='catalog_variant_compare_price_usd_gte_base_price_usd'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
